### ISSUE TITLE
是否需要先把Apk放到下载的目录？

### ISSUE THREAD

**Issue by sdfasffsdf** [weijianfeng/DynamicAppLoader#1]
private ArrayList<LocalApkItem> getApkFromDownload() {         File files = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS);         PackageManager pm = getActivity().getPackageManager();         ArrayList<LocalApkItem> localApkItems = new ArrayList<>();         for (File file : files.listFiles()) {             if (file.exists() && file.getPath().toLowerCase().endsWith(".apk")) {                 final PackageInfo info = pm.getPackageArchiveInfo(file.getPath(), 0);                 localApkItems.add(new LocalApkItem(pm, info, file.getPath()));             }         }         return localApkItems;     }

FATAL EXCEPTION: main
                  Process: com.wjf.dynamicapploader, PID: 24118
                  java.lang.NullPointerException: Attempt to get length of null array
                      at com.wjf.dynamicapploader.fragment.LocalApkFragment.getApkFromDownload(LocalApkFragment.java:132)
                      at com.wjf.dynamicapploader.fragment.LocalApkFragment.loadApks(LocalApkFragment.java:116)
                      at com.wjf.dynamicapploader.fragment.LocalApkFragment.initPlugin(LocalApkFragment.java:107)
                      at com.wjf.dynamicapploader.fragment.LocalApkFragment.onViewCreated(LocalApkFragment.java:77)

**Comment by weijianfeng** [comment]
好久之前写的demo了应该是下载我apk下载链接过期了。插件apk是要先下载，才能被读取和加载。

**Comment by sdfasffsdf** [comment]
点击加号 原理上是去下载对吧？

**Comment by sdfasffsdf** [comment]
大神好！

**Comment by weijianfeng** [comment]
哪个加号，截图给我看下吧，我好久不维护这个了。
